version: 2

sources:
  - name: raw
    database: third-reporter-465909-u3
    schema: gz2_raw_data
    loader: bigquery

    tables:
      - name: sales
        identifier: raw_gz_sales

        config:
          loaded_at_field: CAST(date_date as TIMESTAMP)    # PAS de CAST ici !
          freshness:
            warn_after:
              count: 90
              period: day

        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
            tests:
              - not_null
          - name: revenue
          - name: quantity

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - not_null
              - unique
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
